version: '3.8'

services:
  db:
    image: postgres:15
    container_name: lgtm_db
    environment:
      POSTGRES_DB: lgtm_db
      POSTGRES_USER: lgtm_user
      POSTGRES_PASSWORD: lgtm_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lgtm_user -d lgtm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: